### ISSUE TITLE
Does not work for files with the exw extension

### ISSUE THREAD

**Issue by HighTechForms** [OpenEuphoria/vscode-euphoria#1]
Greg said, "because I whoopsied the configuration... https://github.com/OpenEuphoria/vscode-euphoria/blob/master/package.json#L32
it's just supposed to be a list of dot extensions, and I put in an asterisk for that one"

**Comment by ghaberek** [comment]
Fixed by commit: 0e1580a27c855a7eb9665d0115783a8f9d7833f0
